# Generated by Django 5.2 on 2025-05-06 13:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name you gave this plant', max_length=100)),
                ('species', models.CharField(choices=[('succulent', 'Succulent'), ('fern', 'Fern'), ('flower', 'Flower'), ('tree', 'Tree'), ('herb', 'Herb'), ('other', 'Other')], default='other', max_length=50)),
                ('scientific_name', models.CharField(blank=True, max_length=100, null=True)),
                ('acquired_date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, help_text='e.g., Living room, Balcony', max_length=100)),
                ('watering_interval_days', models.PositiveIntegerField(help_text='How often this plant needs water (in days)')),
                ('last_watered', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Any care notes or reminders')),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plant_images/')),
                ('description', models.CharField(blank=True, help_text='Description of the image', max_length=255)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.plant')),
            ],
        ),
    ]
