# Generated by Django 5.2 on 2025-05-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_plantimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(blank='true', default='fallback.png', upload_to=''),
        ),
    ]
