# Generated by Django 5.2 on 2025-05-06 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_plantimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='last_watered',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
